export const OPEN_MODAL_POPUP = "OPEN_MODAL_POPUP";
export const SET_SUBMIT_POPUP = "SET_SUBMIT_POPUP";
export const OPEN_MODAL_ANTD = "OPEN_MODAL_ANTD";
export const CLOSE_MODAL_ANTD = "CLOSE_MODAL_ANTD";
export const SET_SUBMIT_MODAL_ANTD = "SET_SUBMIT_MODAL_ANTD";
export const SET_TITLE_MODAL_ANTD = "SET_TITLE_MODAL_ANTD";
