export const GET_ALL_TASK_TYPE_REDUX = "GET_ALL_TASK_TYPE_REDUX";
export const GET_ALL_TASK_TYPE_SAGA = "GET_ALL_TASK_TYPE_SAGA";
export const GET_ALL_STATUS_SAGA = "GET_ALL_STATUS_SAGA";
export const GET_ALL_STATUS_REDUX = "GET_ALL_STATUS_REDUX";
export const GET_ALL_PRIORITY_SAGA = "GET_ALL_PRIORITY_SAGA";
export const GET_ALL_PRIORITY_REDUX = "GET_ALL_PRIORITY_REDUX";
export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA";
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA'
export const GET_TASK_DETAIL_REDUX = "GET_TASK_DETAIL_REDUX";
export const SET_DATA_LOADING = "SET_DATA_LOADING";
//Edit
export const UPDATE_STATUS_SAGA ='UPDATE_STATUS_SAGA'
export const UPDATE_PRIORITY_SAGA = "UPDATE_PRIORITY_SAGA";
export const UPDATE_DESCRIPTION_SAGA = "UPDATE_DESCRIPTION_SAGA";
export const UPDATE_TIME_TRACKING_SAGA = "UPDATE_TIME_TRACKING_SAGA";
export const UPDATE_ESTIMATE_SAGA = "UPDATE_ESTIMATE_SAGA";
export const REMOVE_USER_FROM_TASK = "REMOVE_USER_FROM_TASK";
export const ASSIGN_USER_TASK = 'ASSIGN_USER_TASK'